/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#83cfff",
        "inverse-on-surface": "#ffedea",
        "on-tertiary-fixed": "#001e2e",
        "on-tertiary": "#ffffff",
        "surface-tint": "#bd1119",
        "on-primary": "#ffffff",
        "surface-container-highest": "#fbdbd8",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#3e637e",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#c7e7ff",
        "surface-dim": "#f2d3cf",
        "on-tertiary-container": "#ebf5ff",
        "tertiary": "#005d83",
        "inverse-surface": "#3f2c2a",
        "on-surface-variant": "#5c403d",
        "on-primary-container": "#fff1ef",
        "surface": "#fff8f7",
        "tertiary-container": "#0077a6",
        "on-primary-fixed": "#410002",
        "primary-fixed": "#ffdad6",
        "on-error": "#ffffff",
        "surface-variant": "#fbdbd8",
        "on-surface": "#281716",
        "on-secondary-fixed": "#001e2f",
        "surface-container-high": "#ffe2de",
        "inverse-primary": "#ffb4ab",
        "background": "#fff8f7",
        "surface-container-low": "#fff0ee",
        "secondary-container": "#b9dffe",
        "on-background": "#281716",
        "on-secondary-fixed-variant": "#244a64",
        "secondary-fixed-dim": "#a5cbea",
        "secondary-fixed": "#cae6ff",
        "outline": "#906f6b",
        "on-tertiary-fixed-variant": "#004c6c",
        "primary-fixed-dim": "#ffb4ab",
        "on-primary-fixed-variant": "#93000d",
        "secondary": "#3d627d",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "surface-bright": "#fff8f7",
        "primary-container": "#d62828",
        "on-error-container": "#93000a",
        "outline-variant": "#e5bdb9",
        "primary": "#b20112",
        "surface-container": "#ffe9e6"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "lg": "48px",
        "gutter": "24px",
        "xs": "4px",
        "md": "24px",
        "sm": "12px",
        "xl": "80px",
        "container-max": "1280px",
        "base": "8px"
      },
      fontFamily: {
        "h1": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "h3": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "h2": ["Plus Jakarta Sans", "sans-serif"],
        "plus-jakarta-sans": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "h1": ["48px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "h3": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "600" }],
        "h2": ["32px", { lineHeight: "1.3", fontWeight: "700" }]
      }
    },
  },
  darkMode: "class",
  plugins: [
    require('@tailwindcss/forms'),
  ],
}